# Generated by Django 6.0.5 on 2026-05-16 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('pavillon', models.CharField(default='Pavillon A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAppui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_appui', models.CharField(choices=[('STAGE', 'Appui pour demande de Stage'), ('VISA', "Lettre d'appui pour Visa Études"), ('BOURSE', "Demande d'appui pour Bourse")], default='STAGE', max_length=15)),
                ('motif', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=15)),
                ('fichier_appui', models.FileField(blank=True, null=True, upload_to='appuis_docs/')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_appui', to='polytechnique.etudiantprofil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeLogement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=15)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_logement', to='polytechnique.chambre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_chambre', to='polytechnique.etudiantprofil')),
            ],
            options={
                'unique_together': {('etudiant', 'chambre')},
            },
        ),
    ]
