# Generated by Django 6.0.5 on 2026-05-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnique', '0003_emploidutemps'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='polytechnique.departement'),
        ),
    ]
