# Generated by Django 6.0.5 on 2026-05-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnique', '0004_user_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
