# Generated by Django 6.0.5 on 2026-05-23 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polytechnique', '0005_alter_classe_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAppuiStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=15)),
                ('fichier_appui', models.FileField(blank=True, null=True, upload_to='appuis_stage/')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_appui_stage', to='polytechnique.etudiantprofil')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('convention', models.FileField(blank=True, null=True, upload_to='conventions_stage/')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_stage', to='polytechnique.etudiantprofil')),
            ],
        ),
    ]
